# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Aproximações
email: 
description: > # this means to ignore newlines until "baseurl:"
  Aproximações Sucessivas da Realidade.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.fabiomaia.org" # the base hostname & protocol for your site
twitter_username: fwmm
github_username:  fwmm
contact: fwmmaia@gmail.com

# Build settings
markdown: kramdown
